<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Product;
use App\Models\Stock;
use App\Models\Category;
use App\Models\Supplier;

class BulkProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $products = [
            // Personal Care (Category 5) - 7 products
            [
                'product_code' => 'PRD011',
                'barcode' => '4800010001235',
                'product_name' => 'Colgate Total 150g',
                'description' => 'Colgate Total toothpaste with fluoride 150g',
                'category_id' => 5,
                'supplier_id' => 1,
                'cost_price' => 85.00,
                'selling_price' => 115.00,
                'unit' => 'pcs',
                'stock_quantity' => 50,
            ],
            [
                'product_code' => 'PRD012',
                'barcode' => '4800067011034',
                'product_name' => 'Safeguard White 130g',
                'description' => 'Safeguard Pure White bar soap 130g',
                'category_id' => 5,
                'supplier_id' => 1,
                'cost_price' => 38.00,
                'selling_price' => 45.00,
                'unit' => 'pcs',
                'stock_quantity' => 100,
            ],
            [
                'product_code' => 'PRD013',
                'barcode' => '4800019123457',
                'product_name' => 'H&S Menthol 170ml',
                'description' => 'Head & Shoulders Cool Menthol shampoo 170ml',
                'category_id' => 5,
                'supplier_id' => 1,
                'cost_price' => 120.00,
                'selling_price' => 155.00,
                'unit' => 'bottle',
                'stock_quantity' => 30,
            ],
            [
                'product_code' => 'PRD014',
                'barcode' => '4800110022334',
                'product_name' => 'Panteene Smooth 150ml',
                'description' => 'Pantene Smooth & Silky conditioner 150ml',
                'category_id' => 5,
                'supplier_id' => 1,
                'cost_price' => 110.00,
                'selling_price' => 140.00,
                'unit' => 'bottle',
                'stock_quantity' => 30,
            ],
            [
                'product_code' => 'PRD015',
                'barcode' => '4800888123450',
                'product_name' => 'Rexona Men Ice 50ml',
                'description' => 'Rexona Men Ice Cool deodorant roll-on 50ml',
                'category_id' => 5,
                'supplier_id' => 1,
                'cost_price' => 95.00,
                'selling_price' => 125.00,
                'unit' => 'pcs',
                'stock_quantity' => 40,
            ],
            [
                'product_code' => 'PRD016',
                'barcode' => '4800888123467',
                'product_name' => 'Rexona Women 50ml',
                'description' => 'Rexona Women Shower Clean deodorant roll-on 50ml',
                'category_id' => 5,
                'supplier_id' => 1,
                'cost_price' => 95.00,
                'selling_price' => 125.00,
                'unit' => 'pcs',
                'stock_quantity' => 40,
            ],
            [
                'product_code' => 'PRD017',
                'barcode' => '4806518123456',
                'product_name' => 'Master Oil Control 135ml',
                'description' => 'Master Deep Cleanser Oil Control 135ml',
                'category_id' => 5,
                'supplier_id' => 1,
                'cost_price' => 85.00,
                'selling_price' => 110.00,
                'unit' => 'bottle',
                'stock_quantity' => 25,
            ],

            // Frozen Goods (Category 6) - 8 products
            [
                'product_code' => 'PRD018',
                'barcode' => '4800012356789',
                'product_name' => 'Purefoods Hotdog 1kg',
                'description' => 'Purefoods Tender Juicy Hotdog Classic 1kg',
                'category_id' => 6,
                'supplier_id' => 2,
                'cost_price' => 185.00,
                'selling_price' => 210.00,
                'unit' => 'pack',
                'stock_quantity' => 20,
            ],
            [
                'product_code' => 'PRD019',
                'barcode' => '4800012356796',
                'product_name' => 'Tender Juicy 500g',
                'description' => 'Purefoods Tender Juicy Hotdog Classic 500g',
                'category_id' => 6,
                'supplier_id' => 2,
                'cost_price' => 95.00,
                'selling_price' => 115.00,
                'unit' => 'pack',
                'stock_quantity' => 30,
            ],
            [
                'product_code' => 'PRD020',
                'barcode' => '4800012356802',
                'product_name' => 'CDO Burger Patty 250g',
                'description' => 'CDO Beef Burger Patties 250g (6pcs)',
                'category_id' => 6,
                'supplier_id' => 2,
                'cost_price' => 55.00,
                'selling_price' => 75.00,
                'unit' => 'pack',
                'stock_quantity' => 40,
            ],
            [
                'product_code' => 'PRD021',
                'barcode' => '4800012356819',
                'product_name' => 'Mekeni Tocino 225g',
                'description' => 'Mekeni Pork Tocino Sweet 225g',
                'category_id' => 6,
                'supplier_id' => 2,
                'cost_price' => 65.00,
                'selling_price' => 85.00,
                'unit' => 'pack',
                'stock_quantity' => 35,
            ],
            [
                'product_code' => 'PRD022',
                'barcode' => '4800012356826',
                'product_name' => 'Magnolia Chicken 1kg',
                'description' => 'Magnolia Frozen Whole Chicken 1kg',
                'category_id' => 6,
                'supplier_id' => 2,
                'cost_price' => 165.00,
                'selling_price' => 195.00,
                'unit' => 'pcs',
                'stock_quantity' => 15,
            ],
            [
                'product_code' => 'PRD023',
                'barcode' => '4800012356833',
                'product_name' => 'Bounty Fresh Wings 500g',
                'description' => 'Bounty Fresh Frozen Chicken Wings 500g',
                'category_id' => 6,
                'supplier_id' => 2,
                'cost_price' => 110.00,
                'selling_price' => 135.00,
                'unit' => 'pack',
                'stock_quantity' => 25,
            ],
            [
                'product_code' => 'PRD024',
                'barcode' => '4800012356840',
                'product_name' => 'Argentina Longganisa 250g',
                'description' => 'Argentina Pork Longganisa Skinless 250g',
                'category_id' => 6,
                'supplier_id' => 2,
                'cost_price' => 48.00,
                'selling_price' => 62.00,
                'unit' => 'pack',
                'stock_quantity' => 45,
            ],
            [
                'product_code' => 'PRD025',
                'barcode' => '4800012356857',
                'product_name' => 'Selecta Vanilla 1.5L',
                'description' => 'Selecta Super Thick Vanilla Ice Cream 1.5L',
                'category_id' => 6,
                'supplier_id' => 2,
                'cost_price' => 210.00,
                'selling_price' => 245.00,
                'unit' => 'tub',
                'stock_quantity' => 10,
            ],

            // Canned Goods (Category 3) - 7 products
            [
                'product_code' => 'PRD026',
                'barcode' => '4800016644023',
                'product_name' => 'Century Tuna 180g',
                'description' => 'Century Tuna Flakes in Oil 180g',
                'category_id' => 3,
                'supplier_id' => 3,
                'cost_price' => 45.00,
                'selling_price' => 58.00,
                'unit' => 'can',
                'stock_quantity' => 60,
            ],
            [
                'product_code' => 'PRD027',
                'barcode' => '4800016644030',
                'product_name' => 'Century Tuna Hot 180g',
                'description' => 'Century Tuna Flakes Hot & Spicy 180g',
                'category_id' => 3,
                'supplier_id' => 3,
                'cost_price' => 46.00,
                'selling_price' => 60.00,
                'unit' => 'can',
                'stock_quantity' => 55,
            ],
            [
                'product_code' => 'PRD028',
                'barcode' => '4800016123456',
                'product_name' => 'Mega Sardines Red 155g',
                'description' => 'Mega Sardines in Tomato Sauce 155g',
                'category_id' => 3,
                'supplier_id' => 3,
                'cost_price' => 22.00,
                'selling_price' => 28.00,
                'unit' => 'can',
                'stock_quantity' => 120,
            ],
            [
                'product_code' => 'PRD029',
                'barcode' => '4800016123463',
                'product_name' => 'Mega Sardines Green 155g',
                'description' => 'Mega Sardines in Tomato Sauce with Chili 155g',
                'category_id' => 3,
                'supplier_id' => 3,
                'cost_price' => 22.00,
                'selling_price' => 28.00,
                'unit' => 'can',
                'stock_quantity' => 100,
            ],
            [
                'product_code' => 'PRD030',
                'barcode' => '4800112233445',
                'product_name' => 'Hormel Spam 340g',
                'description' => 'Spam Luncheon Meat Classic 340g',
                'category_id' => 3,
                'supplier_id' => 3,
                'cost_price' => 165.00,
                'selling_price' => 195.00,
                'unit' => 'can',
                'stock_quantity' => 20,
            ],
            [
                'product_code' => 'PRD031',
                'barcode' => '4800112233452',
                'product_name' => 'Libby\'s Sausage 130g',
                'description' => 'Libby\'s Vienna Sausage 130g',
                'category_id' => 3,
                'supplier_id' => 3,
                'cost_price' => 45.00,
                'selling_price' => 62.00,
                'unit' => 'can',
                'stock_quantity' => 40,
            ],
            [
                'product_code' => 'PRD032',
                'barcode' => '4800112233469',
                'product_name' => 'Del Monte Corn 425g',
                'description' => 'Del Monte Whole Kernel Corn 425g',
                'category_id' => 3,
                'supplier_id' => 3,
                'cost_price' => 52.00,
                'selling_price' => 68.00,
                'unit' => 'can',
                'stock_quantity' => 30,
            ],

            // Beverages (Category 1) - 8 products
            [
                'product_code' => 'PRD033',
                'barcode' => '4800123567890',
                'product_name' => 'Nescafe Classic 100g',
                'description' => 'Nescafe Classic Instant Coffee 100g jar',
                'category_id' => 1,
                'supplier_id' => 1,
                'cost_price' => 125.00,
                'selling_price' => 160.00,
                'unit' => 'bottle',
                'stock_quantity' => 40,
            ],
            [
                'product_code' => 'PRD034',
                'barcode' => '4800123567906',
                'product_name' => 'Milo 300g',
                'description' => 'Milo Chocolate Malt Drink 300g pack',
                'category_id' => 1,
                'supplier_id' => 1,
                'cost_price' => 115.00,
                'selling_price' => 145.00,
                'unit' => 'pack',
                'stock_quantity' => 45,
            ],
            [
                'product_code' => 'PRD035',
                'barcode' => '4800123567913',
                'product_name' => 'Natures Spring 500ml',
                'description' => 'Nature\'s Spring Purified Water 500ml',
                'category_id' => 1,
                'supplier_id' => 1,
                'cost_price' => 8.00,
                'selling_price' => 12.00,
                'unit' => 'bottle',
                'stock_quantity' => 200,
            ],
            [
                'product_code' => 'PRD036',
                'barcode' => '4800123567920',
                'product_name' => 'Natures Spring 1.5L',
                'description' => 'Nature\'s Spring Purified Water 1.5L',
                'category_id' => 1,
                'supplier_id' => 1,
                'cost_price' => 18.00,
                'selling_price' => 25.00,
                'unit' => 'bottle',
                'stock_quantity' => 100,
            ],
            [
                'product_code' => 'PRD037',
                'barcode' => '4800123567937',
                'product_name' => 'Gatorade Blue 500ml',
                'description' => 'Gatorade Blue Bolt Sports Drink 500ml',
                'category_id' => 1,
                'supplier_id' => 1,
                'cost_price' => 38.00,
                'selling_price' => 45.00,
                'unit' => 'bottle',
                'stock_quantity' => 60,
            ],
            [
                'product_code' => 'PRD038',
                'barcode' => '4800123567944',
                'product_name' => 'Gatorade Lemon 500ml',
                'description' => 'Gatorade Lemon Lime Sports Drink 500ml',
                'category_id' => 1,
                'supplier_id' => 1,
                'cost_price' => 38.00,
                'selling_price' => 45.00,
                'unit' => 'bottle',
                'stock_quantity' => 60,
            ],
            [
                'product_code' => 'PRD039',
                'barcode' => '4800123567951',
                'product_name' => 'C2 Green Tea 500ml',
                'description' => 'C2 Green Tea Apple Flavor 500ml',
                'category_id' => 1,
                'supplier_id' => 1,
                'cost_price' => 22.00,
                'selling_price' => 28.00,
                'unit' => 'bottle',
                'stock_quantity' => 80,
            ],
            [
                'product_code' => 'PRD040',
                'barcode' => '4800123567968',
                'product_name' => 'Red Bull 250ml',
                'description' => 'Red Bull Energy Drink 250ml can',
                'category_id' => 1,
                'supplier_id' => 1,
                'cost_price' => 65.00,
                'selling_price' => 85.00,
                'unit' => 'can',
                'stock_quantity' => 40,
            ],
        ];

        foreach ($products as $productData) {
            $stockQty = $productData['stock_quantity'];
            unset($productData['stock_quantity']);
            
            // Add required created_by field
            $productData['created_by'] = 1;
            
            $product = Product::create($productData);
            
            Stock::create([
                'product_id' => $product->id,
                'quantity' => $stockQty,
                'min_quantity' => 10,
                'max_quantity' => $stockQty * 2,
                'location' => 'Aisle ' . rand(1, 5)
            ]);
        }
    }
}
